services:
  - type: web
    name: pokemon-deckbuilder-app
    runtime: go
    plan: free
    buildCommand: go build -trimpath -o server .
    startCommand: ./server
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
